### ISSUE TITLE
v3 Final Release Checklist

### ISSUE THREAD

**Issue by jaredcnance** [json-api-dotnet/JsonApiDotNetCore#447]
- [x] Improve deprecation error on `SortQuery` to identify what string should b used for the attr name
- [x] Null reference exception if `JsonApiContext` is null during construction of `BaseAttrQuery`:
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/89c38dc19c3eaabf7a4738e8c4a2f00b3a05fa18/src/JsonApiDotNetCore/Internal/Query/BaseAttrQuery.cs#L44
```
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at JsonApiDotNetCore.Internal.Query.BaseAttrQuery.GetAttribute(String attribute) in C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Internal\Query\BaseAttrQuery.cs:line 44
   at JsonApiDotNetCore.Internal.Query.BaseAttrQuery..ctor(IJsonApiContext jsonApiContext, BaseQuery baseQuery) in C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Internal\Query\BaseAttrQuery.cs:line 29
   at JsonApiDotNetCore.Internal.Query.AttrSortQuery..ctor(IJsonApiContext jsonApiContext, SortQuery sortQuery) in C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Internal\Query\AttrSortQuery.cs:line 10
   at JsonApiDotNetCore.Extensions.IQueryableExtensions.Sort[TSource](IQueryable`1 source, IJsonApiContext jsonApiContext, SortQuery sortQuery) in C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Extensions\IQueryableExtensions.cs:line 62

...
```

This likely only occurs during tests where the context was not correctly mocked.

- [x] Write final release notes
- [x] Completed integration into canary production system
