### ISSUE TITLE
Umbrella: pending work for v4

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#693]
This tracking issue lists work to consider before release of JADNC v4.

## v4.0.0-alpha5 (released)
- [x] Code quality #691
- [x] Bugfix #687
- [x] Bugfix #631
- [x] Memory leak #450
- [x] Params in paging links #276
- [x] SourceLink #692
- [x] Fail on Patch ID mismatch #702
- [x] Hooks ~#623~ -> #717
- [x] Review logging #689
- [x] Encoding bugfix #408
- [x] Error handling #655
- [x] json:api spec compliance #577
- [x] Parallel tests #485
- [x] Auto-inclusion #652
- [x] Default attribute capabilities #707
- [x] Bugfix #708
- [x] Bugfix #725
- [x] Bugfix #724
- [x] Context injection #657
- [x] Validation #472

## v4.0.0-beta1
- [x] Fixed: missing property setter in options #742
- [x] Fixed: GetDefaultSortOrder is never called #736
- [x] Fix in error handler #749
- [x] Fixes sorting on multiple fields #745
- [x] Fixed: error when setting non-string default filter #754
- [x] Filter validation fix #659
- [x] Cleanup example projects #744
- [x] Improved error message in serializer #270
- [x] Documentation updates #741
- [x] Cleanup UseJsonApi #733
- [x] Review all TODOs in code and assess severity #759
- [x] Delete response causes exception in Kestrel #760
- [x] Namespace not honored when using relative links #763
- [x] Composable filters and deeply nested queries #792
  Fixes #788, #787, #764, #761, #758, #757, #751, #748, #747, #738, #551, #444, #217, #183, #176
- [x] Review public API surface (namespaces and publicly exposed types) #734
- [x] More documentation updates #567
- [x] Fix: Routing does not respect custom resource name #786
- [x] ... and a few more

**Comment by bart-degreed** [comment]
@maurei as requested, my wish list. Feel free to edit.

**Comment by bebizzle** [comment]
@maurei - quick question, when are you guys planning to release the next alpha version? My team and I have noticed some divergence between master and what is in Nuget.

**Comment by rachael-ross** [comment]
Any idea on release timing?

**Comment by bart-degreed** [comment]
Closing this, because as a project contributor I can now use (open/close/reassign/label) issues directly.
