### ISSUE TITLE
Review public API surface

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#734]
Things I'd like to change:

- [x] Rename 'entity' parameters to 'resource' in DefaultResourceService
- [x] Rename DefaultResourceRepository to EntityFrameworkCoreRepository (and update variable/parameter names likewise)
- [x] Move all types required for basic usage into JADNC's non-internal namespace. Advanced usage, like custom Service/Repository/ResourceDefinition and query filters can be in Internal namespaces. This should clarify our intent on taking breaking changes.
- [x] Make `options.DefaultPageSize` nullable (disallow setting to 0)
- [x] Rename T in `JsonApiController<T>` to TResource
- [x] Rename IQueryParameterParser to IQueryStringParser (it parses all types, not a single one)
- [x] Replace `IEnumerable<>` / `List<>` with `IReadOnlyCollection<>`
- [x] Review null checks
- [x] Validate input parameters on public members, validate options.
- [x] Rename CurrentRequest to JsonApiRequest

Other
- [x] Remove the various .gitignore files that are spread around in the repo, and update the root version from https://github.com/github/gitignore/blob/master/VisualStudio.gitignore - #743
- [x] Cleanup launchsettings.json, enable https - #744
- [x] Cleanup excessive logging in AppVeyor - #744

**Comment by maurei** [comment]
>  Rename DefaultResourceRepository to DefaultEntityRepository (and update 
variable/parameter names likewise)

What would be the motivation for this?

**Comment by bart-degreed** [comment]
It is an implementation of a resource repository that uses ORM entities. Other implementations could be named AmazonResourceService, CachingRedisRepository etc.
